import keyboard
import pyautogui
import time
from pynput.mouse import Button, Controller
pyautogui.PAUSE = 0.01
#keyboard.press_and_release('m')
mouse = Controller()

#A minecraft old duper script for old shopgui plugin
pyautogui.FAILSAFE = False
qq = 0
while True:
     keyboard.wait('m')
     keyboard.press_and_release('t')
     time.sleep(0.1)
     keyboard.press_and_release('/')
     time.sleep(0.1)
     keyboard.press_and_release('s')
     time.sleep(0.1)
     keyboard.press_and_release('h')
     time.sleep(0.1)
     keyboard.press_and_release('o')
     time.sleep(0.1)
     keyboard.press_and_release('p')
     time.sleep(0.1)
     keyboard.press_and_release('enter')
     time.sleep(0.1)
     pyautogui.moveTo(738, 340)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(1037, 560)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(1037, 560)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(1037, 560)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(739, 226)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(1187, 384)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(1187, 384)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(960, 293)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(960, 293)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(960, 293)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(960, 293)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(960, 293)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(960, 293)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(960, 293)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(960, 293)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(960, 293)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     pyautogui.moveTo(960, 293)
     time.sleep(0.1)
     pyautogui.click()
     time.sleep(0.1)
     keyboard.press_and_release('esc')
     time.sleep(0.1)
     keyboard.press_and_release('e')
     time.sleep(0.1)
     #rom
     d = 64
     u = 11
     for j in range(u):
          for i in range(d):
               time.sleep(0.01)
               pyautogui.moveTo(512, 475) #gomb recipe
               time.sleep(0.01)
               time.sleep(0.0001)
               pyautogui.click()
      #
          for i in range(d):
              time.sleep(0.01)
              pyautogui.moveTo(1559, 344)
              time.sleep(0.01)
              time.sleep(0.0001)
              pyautogui.click()
     #rom
     time.sleep(0.1)
     keyboard.press_and_release('esc')
     time.sleep(0.01)
     pyautogui.click()

     time.sleep(0.1)
     keyboard.press_and_release('t')
     time.sleep(0.1)
     keyboard.press_and_release('/')
     time.sleep(0.1)
     keyboard.press_and_release('s')
     time.sleep(0.1)
     keyboard.press_and_release('e')
     time.sleep(0.1)
     keyboard.press_and_release('l')
     time.sleep(0.1)
     keyboard.press_and_release('l')
     time.sleep(0.1)
     keyboard.press_and_release('a')
     time.sleep(0.1)
     keyboard.press_and_release('l')
     time.sleep(0.1)
     keyboard.press_and_release('l')
     time.sleep(0.1)
     keyboard.press_and_release('enter')
     time.sleep(0.1)
     #eddig
     #x, y = pyautogui.position()
    # time.sleep(0.01)

   #  time.sleep(0.01)
  #   pyautogui.click()
 #    print(x,y)